### ISSUE TITLE
Two TODOs

### ISSUE THREAD

**Issue by szepeviktor** [helgatheviking/Nav-Menu-Roles#46]
```xml
    <rule ref="WordPress-Core">
        <!-- TODO Use strict comparisions! -->
        <exclude name="WordPress.PHP.StrictComparisons"/>
        <!-- TODO Tell translators what is up! -->
        <exclude name="WordPress.WP.I18n"/>
    </rule>
```
- 17×StrictComparisons
- 5×I18n

Start by simply remove exclude-s.

**Comment by szepeviktor** [comment]
@helgatheviking Hello 👋🏻 

PHPCS says there are 42 problems 😭

**Comment by helgatheviking** [comment]
Hi :wave: Hmm... I just fixed a bunch and now I am only seeing the following

>FILE: src/customize-controls.js
-----------------------------------------------------------------------------------------------------------------------
FOUND 3 ERRORS AFFECTING 3 LINES
-----------------------------------------------------------------------------------------------------------------------
 13 | ERROR | [x] Multi-line function call not indented correctly; expected 8 spaces but found 12
    |       |     (PEAR.Functions.FunctionCallSignature.Indent)
 16 | ERROR | [x] Multi-line function call not indented correctly; expected 20 spaces but found 24
    |       |     (PEAR.Functions.FunctionCallSignature.Indent)
 39 | ERROR | [x] Multi-line function call not indented correctly; expected 12 spaces but found 16
    |       |     (PEAR.Functions.FunctionCallSignature.Indent)
    
And I can't seem to fix it, because when I do, it gives me a different error about tabs being wrong. So damned if you do, damned if you don't.

**Comment by szepeviktor** [comment]
PEAR comes from a time when there was no _fat arrow function_.

**Comment by helgatheviking** [comment]
That probably explains it. I gave up... a little indentation error isn't going to hurt anybody one way or the other.
