### ISSUE TITLE
Exclude by role

### ISSUE THREAD

**Issue by helgatheviking** [helgatheviking/Nav-Menu-Roles#56]
example:

show item to everyone _Except_ "subscriber" role.

**Comment by helgatheviking** [comment]
+1 https://wordpress.org/support/topic/hide-menu-items-from-users-that-have-a-specific-role/

**Comment by lkraav** [comment]
This goes into quite high development burdain territory, but AutomateWoo rule system is really solid

![image](https://user-images.githubusercontent.com/147228/116554730-34755480-a904-11eb-9717-12a202c0d1ef.png)

Maybe a simpler version could be brainstormed, something that is realistically reachable here.

**Comment by helgatheviking** [comment]
Thanks for the info. I do think that's gonna be more dev work than I want to get into. 

What about an additional display mode?

![image](https://user-images.githubusercontent.com/507025/116563667-76c97200-a8c1-11eb-9195-13354cc782de.png)

though I think that's kinda confusing.

Or another radio toggle after display mode?

![image](https://user-images.githubusercontent.com/507025/116565496-2bb05e80-a8c3-11eb-9115-02a769d8c080.png)

anything there spark an idea?

**Comment by lkraav** [comment]
> Or another radio toggle after display mode? anything there spark an idea?

This is indeed a more simplistic binary rule engine that might work well enough for majority.

Perhaps we can re-use something from Widget Options plugin https://github.com/WidgetOptions/widget-options codebase that seem to have the exact same problem to solve:

![Hide/Show](https://raw.githubusercontent.com/WidgetOptions/widget-options/master/screenshot-1.png)

**Comment by helgatheviking** [comment]
Ahh! that's not bad. So we could go

Hide/Show as a binary choice

and _then_ let the user set who they are hiding/showing to: logged in, logged out, everyone

![image](https://user-images.githubusercontent.com/507025/116581822-f65f3d00-a8d1-11eb-9332-8fac1f8d98a2.png)

still needs better language and I'd probably prefer a toggle there over a radio, but not quite sure how to make that work.

**Comment by consciousimages** [comment]
@helgatheviking - landed on this thread and super happy to see this feature is being considered.  My use case is I want to show one item/link to just one user role (works great!) and a different item to everyone but that same user role. I love the last screenshot because it's so simple.  Paradoxically, that will work for me if it was possible to select both logged in users (with the role selection) AND logged out users for the hide/exclude functionality.  The first idea I had was to show the user roles under 'everyone'... which would also work.  The first idea might be easier to develop... my two cents! :-)

**Comment by helgatheviking** [comment]
"considered" may be too strong of a word. :) I have a lot on my plate right now with my premium plugins... so that does kinda mean the free ones are on the back-burner (or off the stove entirely). 

But if show/hide screenshot makes sense to you, that does help. When I am able to come back to this that should not be too complex. 

Open to PRs if anyone wants to try it!

**Comment by consciousimages** [comment]
@helgatheviking I hear you, and am short of time myself.  That said, it doesn't feel too complex to me either.  I will look into it more...

**Comment by helgatheviking** [comment]
@lkraav and @consciousimages and anyone else interested in this feature... would you care to take a look at this branch?
https://github.com/helgatheviking/Nav-Menu-Roles/tree/issues/56-exclude-by-role
Currently only for the admin nav-menus area, but a start. Would appreciate testing and feedback.

**Comment by helgatheviking** [comment]
for anyone following along, there are some updates and (in theory) it should work in the customizer!

**Comment by lkraav** [comment]
> would you care to take a look at this branch? https://github.com/helgatheviking/Nav-Menu-Roles/tree/issues/56-exclude-by-role Currently only for the admin nav-menus area, but a start. Would appreciate testing and feedback.

Couldn't quite get there during dev time, but looks like we'll go straight to testing this in production now :+1: :+1:

**Comment by helgatheviking** [comment]
Test in prod b/c you only live once! 🤣

**Comment by lkraav** [comment]
> Test in prod b/c you only live once! rofl

F'shizzle. First question popped up, more related to Memberships integration (but it's possible to also multi-role WP users):

if you want to Hide a menu item only for a role that is held alone, it seems like currently not possible?

We could probably use some kind of a "Mode" selector:

Role(s) [is / is not / includes / does not include]

Thoughts?

**Comment by helgatheviking** [comment]
Not sure I understand.... can you give an example?  I will say that the testing of whether or not a user cannot do something is a little fuzzy as it's just the negative of `current_user_can()`... which may not always be perfect. 

Remember that we aren't actually checking a role as WP really prefers testing capabilities for who is allowed to do/see what. This does leave a little gray area between WP and this plugin.

Open to other ideas of course...

**Comment by lkraav** [comment]
> Not sure I understand.... can you give an example?

User holds 2 roles: Editor, Customer Success

I want to Hide a menu item for people holding ONLY "Customer Success" role alone.

**Comment by helgatheviking** [comment]
I'm inclined to say that at that level of complexity you might want to build a "pseudo role" to do exactly what you need.

**Comment by jniernberger** [comment]
> I'm inclined to say that at that level of complexity you might want to build a "pseudo role" to do exactly what you need.

Finally able to test this update out myself.  I will report back on this separately in the coming days but did see this thread and @lkraav in my experience this is the correct answer, when I've had complicated sites with multi-role user accounts you will start to have issues that are difficult to troubleshoot because they don't make a lot of sense... inevitably combining the two roles into one for the users having the problems has been the fix.

**Comment by consciousimages** [comment]
> I'm inclined to say that at that level of complexity you might want to build a "pseudo role" to do exactly what you need.

Finally able to test this update out myself. I will report back on this separately in the coming days but did see this thread and @lkraav in my experience this is the correct answer, when I've had complicated sites with multi-role user accounts you will start to have issues that are difficult to troubleshoot because they don't make a lot of sense... inevitably combining the two roles into one for the users having the problems has been the fix.

**Comment by lkraav** [comment]
> inevitably combining the two roles into one for the users having the problems has been the fix.

Sure, for users, but this strategy can't sanely be done for https://github.com/helgatheviking/nav-menu-roles-woocommerce-memberships
