### ISSUE TITLE
Tested for 5.9?

### ISSUE THREAD

**Issue by TheGreatRefrigerator** [helgatheviking/Nav-Menu-Roles#60]
Hi, we use this plugin on WP 5.8 already and it seems still to be working.
Just wondering because the readme.txt states, that it is only tested until 5.7 but the plugin still getting new updates.

Was it just forgotten to increase the compatible version or is it not tested on the newest WP versions?
Best regards

**Comment by helgatheviking** [comment]
Hi... yes, I forget to update that in my last version bump. The plugin is not abandoned, but I can't always test the plugin rigorously against new WP versions due to time constraints. Luckily, the plugin is simple enough that most WP versions have no impact. 6.0 is coming out at the end of the month though... if you were able to test NMR against WP 6.0 that would be a big help.
